### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by dizzyrue** [Parskatt/RoMaV2#17]
When I run the script demo/demo_matched.py, I encounter the following error:
File "/tmp/torchinductor_lsg/jq/cjqaejqmze5kkvat2odpshgevgsonso2eq3kpxreejz6sz2xvvyf.py", line 27945, in call
    buf1888 = empty_strided_cuda((1, 192, 320, 15680), (963379200, 5017600, 15680, 1), torch.float32)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.59 GiB. GPU 0 has a total capacity of 15.67 GiB of which 3.63 GiB is free. Including non-PyTorch memory, this process has 10.61 GiB memory in use. Of the allocated memory 9.47 GiB is allocated by PyTorch, and 908.12 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I would like to ask: does running inference with this model normally require such a large amount of GPU memory?

My GPU has 16 GB of VRAM, and I’m wondering if there is any recommended way to reduce the memory usage (e.g., settings, options, or smaller input sizes) so that demo_matched.py can run successfully on a 16 GB GPU.

**Comment by dizzyrue** [comment]
When I use your custom CUDA kernels, the out-of-memory issue is resolved. Thank you very much for providing the solution!
However, I have a question: in Table 8 of the paper, it shows that even without using the custom CUDA kernels, the memory consumption does not increase significantly. Why am I seeing a large memory spike in my case?

<img width="961" height="545" alt="Image" src="https://github.com/user-attachments/assets/14e22ff2-2b1f-45a0-9fb3-80f60b03b962" />
